export const productData = [
        { 
            id:1,
            title:"Sakiz",
            price:0.5,   
         },
         { 
                id:2,
                title:"Cola",
                price:6,   
             },
             { 
                id:3,
                title:"Ayakkabı",
                price:400,   
             },
             { 
                id:4,
                title:"Araba",
                price:40000,   
             },
]