export const productData = [
        { 
            id:1,
            title:"Motor",
            price:0.5, 
            image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBXLUnA7YN_fLc0x3WYkuh-5DnYyJdZsVepQ&usqp=CAU"  
         },
         { 
                id:2,
                title:"Cola",
                price:6,   
             },
             { 
                id:3,
                title:"Ayakkabı",
                price:400,   
             },
             { 
                id:4,
                title:"Araba",
                price:40000,   
             },
]